#!/usr/bin/env sh

export MYSQL_ROOT_PASSWORD='password'
docker run --restart always --name mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -d mysql:oracle mysqld --default-authentication-plugin=mysql_native_password

export POSTGRES_PASSWORD='password'
docker run --restart always --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -d postgres

docker run --restart always --name redis -p 6379:6379 -d redis --save 60 1 --loglevel warning
