#!/usr/bin/env bash

apt-get update -y || true
apt-get upgrade -y || true
apt-get dist-upgrade -y || true

apt-get install -y sudo curl openssh-server iptables || true

wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -

apt-get install apt-transport-https -y || true

echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

apt-get update -y
apt-get install - y sublime-text

apt-get -y --purge autoremove || true
apt-get -y clean || true
