#!/usr/bin/env bash

if test ! $(which brew); then

  xcode-select --install

  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

fi

brew doctor

taps=(
  caskroom/cask
)

brew tap ${taps[@]}

packages=(
  docker
  docker-machine
  gnupg
  mercurial
  mysql@5.7
  packer
  packer-completion
  postgresql@9.6
  redis@4.0
  rsync
  sqlite
  terraform
  watchman
  yarn
)

brew install "${packages[@]}"
brew prune; brew cleanup

casks=(
  android-studio
  1password
  caskroom/versions/java8
  firefox
  iterm2
  fastlane
  sketch
  sublime-text
  superduper
  tableplus
  transmit
  tripmode
  tower
  vagrant
  virtualbox
  virtualbox-extension-pack
)

brew cask doctor
brew cask install ${casks[@]}

fonts=(
  font-fira-code
  font-lato
  font-open-sans
  font-roboto
  font-source-code-pro
  font-ubuntu
)

brew cask install "${fonts[@]}"

brew cask cleanup

vboxmanage setproperty machinefolder "${HOME}/VMs"
