#!/usr/bin/env bash

if [ ! -f ${HOME}/.installed ]; then

  pmset -a standbydelay 4200
  pmset -a destroyfvkeyonstandby 1 hibernatemode 25

  scutil --set ComputerName `whoami`
  scutil --set HostName `whoami`
  scutil --set LocalHostName `whoami`

  nvram SystemAudioVolume=" "

  /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on || true
  /usr/libexec/ApplicationFirewall/socketfilterfw --setblockall on || true

  chflags nohidden ~/Library

  function set_default {
    defaults write ${1}
  }

  defaults(
    "/Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string `whoami`"
    "com.apple.dock mouse-over-hilite-stack -bool true"
    "NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false"
    'com.apple.print.PrintingPrefs "Quit When Finished" -bool true'
    "com.apple.SoftwareUpdate ScheduleFrequency -int 1"
    "com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true"
    "-currentHost NSGlobalDomain com.apple.mouse.tapBehavior -int 1"
    "NSGlobalDomain com.apple.mouse.tapBehavior -int 1"
    "com.apple.desktopservices DSDontWriteNetworkStores -bool true"
    "com.apple.dock tilesize -int 48"
    "com.apple.dock minimize-to-application -bool true"
    "com.apple.dock enable-spring-load-actions-on-all-items -bool true"
    "com.apple.dock mru-spaces -bool false"
    "com.apple.finder AppleShowAllFiles -bool true"
    "com.apple.screensaver askForPassword -int 1"
    "com.apple.screensaver askForPasswordDelay -int 0"
    'com.apple.Safari HomePage -string "about:blank"'
    "com.apple.Safari ShowFavoritesBar -bool false"
    "com.apple.Safari IncludeInternalDebugMenu -bool true"
    "com.apple.Safari IncludeDevelopMenu -bool true"
    "com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true"
    "com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true"
    "com.apple.Safari UniversalSearchEnabled -bool false"
    "com.apple.Safari SuppressSearchSuggestions -bool true"
    "com.apple.Safari AutoOpenSafeDownloads -bool false"
    "com.apple.terminal StringEncodings -array 4"
    "NSGlobalDomain WebKitDeveloperExtras -bool true"
    "com.apple.CrashReporter DialogType none"
  )

  set_default "${defaults[@]}"

  function disable_agent {
    launchctl unload -w /System/Library/LaunchAgents/com.apple.${1}.plist
  }

  agents=(
    AddressBook.AssistantService
    AddressBook.SourceSync
    AddressBook.ContactsAccountsService
    CalendarAgent
    CallHistoryPluginHelper
    CallHistorySyncHelper
    cloudd
    cloudfamilyrestrictionsd-mac
    cloudpaird
    cloudphotosd
    CloudPhotosConfiguration
    CoreLocationAgent
    facebook.xpc
    findmymacmessenger
    gamed
    icloud.fmfd
    idsremoteurlconnectionagent
    photolibraryd
    rtcreportingd
    SafariCloudHistoryPushAgent
    safaridavclient
    SafariNotificationAgent
    SocialPushAgent
    syncdefaultsd
    telephonyutilities.callservicesd
    weibo.xpc
  )

  disable_agent ${agents[@]}

  function disable_daemon {
    launchctl unload -w /System/Library/LaunchDaemons/com.apple.${1}.plist
  }

  daemons=(
    CrashReporterSupportHelper
    GameController.gamecontrollerd
    SubmitDiagInfo
  )

  disable_daemon ${daemons[@]}

  pfctl -e -f pf.rules

  softwareupdate -ia

fi
