#!/usr/bin/env bash

if [ ! -f ${HOME}/.installed ]; then

  pmset -a standbydelay 4200
  pmset -a destroyfvkeyonstandby 1 hibernatemode 25
  pmset -a sms 0

  scutil --set ComputerName `whoami`
  scutil --set HostName `whoami`
  scutil --set LocalHostName `whoami`

  nvram SystemAudioVolume=" "

  /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on || true
  /usr/libexec/ApplicationFirewall/socketfilterfw --setblockall on || true

  chflags nohidden ~/Library

  function set_default {
    defaults write ${1}
  }

  defaults(
    "/Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string `whoami`"
    "com.apple.dock mouse-over-hilite-stack -bool true"
    'com.apple.print.PrintingPrefs "Quit When Finished" -bool true'
    "com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true"
    "-currentHost NSGlobalDomain com.apple.mouse.tapBehavior -int 1"
    "NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false"
    "NSGlobalDomain com.apple.mouse.tapBehavior -int 1"
    "NSGlobalDomain AppleShowAllExtensions -bool true"
    "com.apple.desktopservices DSDontWriteNetworkStores -bool true"
    "com.apple.dock minimize-to-application -bool true"
    "com.apple.dock enable-spring-load-actions-on-all-items -bool true"
    "com.apple.dock mru-spaces -bool false"
    "com.apple.finder AppleShowAllFiles -bool true"
    'com.apple.Safari HomePage -string "about:blank"'
    "com.apple.Safari ShowFavoritesBar -bool false"
    "com.apple.Safari IncludeDevelopMenu -bool true"
    "com.apple.Safari UniversalSearchEnabled -bool false"
    "com.apple.Safari SuppressSearchSuggestions -bool true"
    "com.apple.Safari AutoOpenSafeDownloads -bool false"
    "com.apple.terminal StringEncodings -array 4"
    "NSGlobalDomain WebKitDeveloperExtras -bool true"
    "com.apple.CrashReporter DialogType none"
    "com.apple.iTunes dontAutomaticallySyncIPods -integer 1"
    "com.apple.TextEdit RichText -int 0"
  )

  set_default "${defaults[@]}"

  pfctl -e -f pf.rules

  softwareupdate -ia

fi
