#!/usr/bin/env bash

if test ! $(which dnsmasq); then

  brew install dnsmasq

  echo "address=/.localhost/127.0.0.1" >> $(brew --prefix)/etc/dnsmasq.conf
  echo "port=53" >> $(brew --prefix)/etc/dnsmasq.conf
  sudo mkdir -p /etc/resolver
  sudo bash -c 'echo "nameserver 127.0.0.1" > /etc/resolver/localhost'

  sudo brew services start dnsmasq

else

  scutil --dns

fi
