#!/usr/bin/env bash

if [ ! -f ${HOME}/.installed ]; then

  sudo -v
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

  ./core
  ./brew
  ./apps
  ./dns
  ../asdf
  ../gem

  touch ${HOME}/.installed

  trimforce enable

fi
