#!/usr/bin/env zsh

git clone https://github.com/sindresorhus/pure.git "${HOME}/.zsh/pure"
git clone https://github.com/zsh-users/zsh-autosuggestions "${HOME}/.zsh/zsh-autosuggestions"
git clone https://github.com/zsh-users/zsh-syntax-highlighting "${HOME}/.zsh/zsh-syntax-highlighting"
git clone https://github.com/zsh-users/zsh-history-substring-search "${HOME}/.zsh/zsh-history-substring-search"
