#!/usr/bin/env bash

if [ ! -d "${HOME}/.asdf" ]; then

  if [[ "$OSTYPE" == "darwin"* ]]; then
    ./macosx/asdf
  fi


  git clone https://github.com/asdf-vm/asdf.git ${HOME}/.asdf --branch v0.5.0

  chmod +x ${HOME}/.asdf/bin/asdf
  chmod +x ${HOME}/.asdf/completions/asdf.bash

  . ${HOME}/.bash_profile

fi

plugins=(
  golang
  nodejs
  python
)

asdf plugin-add ${plugins[@]}

bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

versions=(
  "golang 1.10.10"
  "nodejs 8.15.0"
  "python 2.7.16"
)

asdf install "${versions[@]}"
asdf global "${versions[@]}"
