set -g default-terminal "tmux-256color"

set -g mouse on

# Copy mode
setw -g mode-keys vi
bind ` copy-mode
unbind [
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel 'pbcopy'
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind y run "tmux save-buffer - | pbcopy"
